In [1]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)

[5 7 9]


In [3]:
menu = np.array(['chese', 'bbq', 'veg', 'spicy'])
print(menu)

['chese' 'bbq' 'veg' 'spicy']


In [4]:
prices = [100, 200, 150, 220]
print(prices)

[100, 200, 150, 220]


In [5]:
prices_np = np.array([100, 200, 150, 220])
prices = prices_np * 0.8
print(prices)

[ 80. 160. 120. 176.]


In [6]:
empty_table = np.zeros((2, 3))
print(empty_table)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
full_table = np.ones((3, 3))
print(full_table)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
bbq_boxes = np.full((2, 3), 'bbq')
print(bbq_boxes)

[['bbq' 'bbq' 'bbq']
 ['bbq' 'bbq' 'bbq']]


In [14]:
kids_order = np.random.randint(1, 8, (2, 3))
print(kids_order)

[[6 6 7]
 [7 4 5]]


In [20]:
surprise_toppings = np.random.rand(2, 3)
print(surprise_toppings)

[[0.36985189 0.25838879 0.65000949]
 [0.94807416 0.75854265 0.52111285]]


In [21]:
signature_pizzas = np.identity(3)
print(signature_pizzas)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
delivery_items = np.arange(0, 70, 15)
print(delivery_items)

[ 0 15 30 45 60]


In [24]:
cooking_shifts = np.linspace(0, 70, 5)
print(cooking_shifts)

[ 0.  17.5 35.  52.5 70. ]


In [25]:
orders = np.array(['cheese', 'veg', 'spicy', 'bbq'])
print(orders[2])

spicy


In [26]:
print(orders[:2])

['cheese' 'veg']


In [28]:
sales = np.array([2000, 1500, 8000, 3500])
print("Max sales index : ", np.argmax(sales))
print("Max sales : ", np.max(sales))

Max sales index :  2
Max sales :  8000


In [ ]:
print("Min sales ")